# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  database: test_app
  username: root
  password:
  port: 3306
  
test:
  adapter: mysql
  database: test_app
  username: root
  password:
  port: 3306  